splitter:
  root: DATA_SPLITS
  class_name: splitter.GraphPropPredSplitter
  args:
    n_outer_folds: 1
    n_inner_folds: 1
    seed: -1
    stratify: False
    shuffle: False
    inner_val_ratio: -1
    outer_val_ratio: -1
    test_ratio: -1
dataset:
  root: DATA/
  class_name: dataset.GraphPropertyPrediction
  args:
    root: DATA/
    name: SSSP